<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/public/assets/css/animate.css" />
<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/public/assets/css/bootstrap.css" />
<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/public/assets/css/bootstrap-fs-modal.css" />
<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/public/assets/css/bootstrap-select.css" />
<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/public/assets/css/adminlte.css" />
<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/public/assets/css/adminlte-miscellaneous.css" />
<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/public/assets/css/box-widget.css" />
<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/public/assets/css/datatables.min.css" />
<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/public/assets/css/jquery.daterange.css" />
<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/public/assets/css/jquery.fileupload-noscript.css" />
<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/public/assets/css/jquery.fileupload.css" />
<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/public/assets/css/font-awesome.css" />
<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/public/assets/css/all.css" />
<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/public/assets/css/v4-shims.min.css" />
<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/public/assets/flaticon/flaticon.css" />
<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/public/assets/fontastic/styles.css" />
<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/public/assets/css/fonts.css" />
<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/public/assets/css/w3.css" />
<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/public/assets/css/pignose.calendar.css" />
<link rel="stylesheet" href="<?php echo URL_ROOT; ?>/public/custom-assets/css/custom.css" />
